### ISSUE TITLE
npm install -- wow! this is a serious issue

### ISSUE THREAD

**Issue by AiFxApp** [themesberg/volt-laravel-dashboard#18]
npm install
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,      
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated       
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.  
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! code 1
npm ERR! path C:\Users\teren\Downloads\volt-laravel-dashboard-master\node_modules\gulp-sass\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Users\teren\Downloads\volt-laravel-dashboard-master\node_modules\gulp-sass\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Users\\teren\\Downloads\\volt-laravel-dashboard-master\\node_modules\\gulp-sass\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@17.5.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\teren\Downloads\volt-laravel-dashboard-master\node_modules\gulp-sass\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\teren\Downloads\volt-laravel-dashboard-master\node_modules\gulp-sass\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\teren\Downloads\volt-laravel-dashboard-master\node_modules\gulp-sass\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\teren\Downloads\volt-laravel-dashboard-master\node_modules\gulp-sass\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\teren\Downloads\volt-laravel-dashboard-master\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\teren\Downloads\volt-laravel-dashboard-master\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\teren\Downloads\volt-laravel-dashboard-master\node_modules\gulp-sass\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\teren\Downloads\volt-laravel-dashboard-master\node_modules\gulp-sass\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\teren\Downloads\volt-laravel-dashboard-master\node_modules\gulp-sass\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\teren\Downloads\volt-laravel-dashboard-master\node_modules\gulp-sass\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\teren\Downloads\volt-laravel-dashboard-master\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\teren\Downloads\volt-laravel-dashboard-master\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python C:\Python310\python.EXE
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Python310\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:399:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1090:16)
npm ERR! gyp ERR! stack     at Socket.<anonymous> (node:internal/child_process:449:11)        
npm ERR! gyp ERR! stack     at Socket.emit (node:events:526:28)
npm ERR! gyp ERR! stack     at Pipe.<anonymous> (node:net:687:12)
npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\teren\\Downloads\\volt-laravel-dashboard-master\\node_modules\\gulp-sass\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\Users\teren\Downloads\volt-laravel-dashboard-master\node_modules\gulp-sass\node_modules\node-sass
npm ERR! gyp ERR! node -v v17.5.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\teren\AppData\Local\npm-cache\_logs\2022-05-16T01_21_54_973Z-debug-0.logPS C:\Users\teren\Downloads\volt-laravel-dashboard-master> npm audit fix
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,      
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated       
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! code 1
npm ERR! path C:\Users\teren\Downloads\volt-laravel-dashboard-master\node_modules\gulp-sass\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Users\teren\Downloads\volt-laravel-dashboard-master\node_modules\gulp-sass\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Users\\teren\\Downloads\\volt-laravel-dashboard-master\\node_modules\\gulp-sass\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@17.5.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\teren\Downloads\volt-laravel-dashboard-master\node_modules\gulp-sass\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\teren\Downloads\volt-laravel-dashboard-master\node_modules\gulp-sass\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\teren\Downloads\volt-laravel-dashboard-master\node_modules\gulp-sass\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\teren\Downloads\volt-laravel-dashboard-master\node_modules\gulp-sass\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\teren\Downloads\volt-laravel-dashboard-master\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\teren\Downloads\volt-laravel-dashboard-master\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\teren\Downloads\volt-laravel-dashboard-master\node_modules\gulp-sass\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\teren\Downloads\volt-laravel-dashboard-master\node_modules\gulp-sass\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\teren\Downloads\volt-laravel-dashboard-master\node_modules\gulp-sass\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\teren\Downloads\volt-laravel-dashboard-master\node_modules\gulp-sass\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\teren\Downloads\volt-laravel-dashboard-master\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\teren\Downloads\volt-laravel-dashboard-master\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python C:\Python310\python.EXE
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Python310\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:399:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1090:16)
npm ERR! gyp ERR! stack     at Socket.<anonymous> (node:internal/child_process:449:11)        
npm ERR! gyp ERR! stack     at Socket.emit (node:events:526:28)
npm ERR! gyp ERR! stack     at Pipe.<anonymous> (node:net:687:12)
npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\teren\\Downloads\\volt-laravel-dashboard-master\\node_modules\\gulp-sass\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\Users\teren\Downloads\volt-laravel-dashboard-master\node_modules\gulp-sass\node_modules\node-sass
npm ERR! gyp ERR! node -v v17.5.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\teren\AppData\Local\npm-cache\_logs\2022-05-16T01_25_59_363Z-debug-0.log
PS C:\Users\teren\Downloads\volt-laravel-dashboard-master>

**Comment by teamupdivision** [comment]
Hi @AiFxApp,

Thank you for using our products!

Can you please try to delete **package-lock.json** and then run **npm install** again? This should solve your issue.

Please let us know if we can help you with any additional information. 

Best,
UPDIVISION Team

**Comment by teamupdivision** [comment]
Hi @AiFxApp,

We wanted to check in with you to see if you managed to solve your issue. Please let us if we can help in any other way.

Best,
UPDIVISION Team

**Comment by rzki** [comment]
Hi! @teamupdivision, thank you for this amazing templates! I am encountered this error too and followed the instruction you guys gave above, and sadly removing package-lock.json doesn't solve the problem. Maybe you guys have solution regarding this? Would've love to use this template but encountering this error reduced the experience i get from the demo. Thank you

**Comment by teamupdivision** [comment]
Hi @rzki 

Please make sure that you have the last versions of node and npm. Or you can verify them with the following commands `node -v` and `npm -v` and let us know what you get.

At the moment, we cannot reproduce your errors and we think this might be the issue. Please inform us if this solved anything, or if you need further assistance.

Best,
UPDIVISION Team

**Comment by rzki** [comment]
hi @teamupdivision , thanks for your reply! fortunately, i was able to install the npm packages successfully by installing npm-check-updates and updated the dependencies from there. However, when i run `npm install`, some of the packages with high & critical vulnerabilities cannot be audited, is this okay? if it's okay, then i'm good

**Comment by teamupdivision** [comment]
Hi @rzki,

We're glad you were able to solve your issue. As for the packages that can't be audited, none of them are critical, so it's ok.

Please let us know if you need any extra info.

Best,
UPDIVISION Team
